//------------------------------------------------------------------------------
// <auto-generated>
//     Este código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações a este ficheiro poderão provocar um comportamento incorrecto e perder-se-ão se
//     o código for regenerado.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Este código-fonte foi gerado automaticamente por Microsoft.VSDesigner, Versão 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace FormsGestaoHotelariaAPISoap.ServiceCliente {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="GestaoHotelariaSoap", Namespace="http://www.ipca.pt/gestaohotelaria/cliente")]
    public partial class GestaoHotelaria : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback CriarReservaOperationCompleted;
        
        private System.Threading.SendOrPostCallback AlterarOuCancelarReservaOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public GestaoHotelaria() {
            this.Url = global::FormsGestaoHotelariaAPISoap.Properties.Settings.Default.FormsGestaoHotelariaAPISoap_ServiceCliente_GestaoHotelaria;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event CriarReservaCompletedEventHandler CriarReservaCompleted;
        
        /// <remarks/>
        public event AlterarOuCancelarReservaCompletedEventHandler AlterarOuCancelarReservaCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.ipca.pt/gestaohotelaria/cliente/CriarReserva", RequestNamespace="http://www.ipca.pt/gestaohotelaria/cliente", ResponseNamespace="http://www.ipca.pt/gestaohotelaria/cliente", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string CriarReserva(string email, string Quarto) {
            object[] results = this.Invoke("CriarReserva", new object[] {
                        email,
                        Quarto});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CriarReservaAsync(string email, string Quarto) {
            this.CriarReservaAsync(email, Quarto, null);
        }
        
        /// <remarks/>
        public void CriarReservaAsync(string email, string Quarto, object userState) {
            if ((this.CriarReservaOperationCompleted == null)) {
                this.CriarReservaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCriarReservaOperationCompleted);
            }
            this.InvokeAsync("CriarReserva", new object[] {
                        email,
                        Quarto}, this.CriarReservaOperationCompleted, userState);
        }
        
        private void OnCriarReservaOperationCompleted(object arg) {
            if ((this.CriarReservaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CriarReservaCompleted(this, new CriarReservaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.ipca.pt/gestaohotelaria/cliente/AlterarOuCancelarReserva", RequestNamespace="http://www.ipca.pt/gestaohotelaria/cliente", ResponseNamespace="http://www.ipca.pt/gestaohotelaria/cliente", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string AlterarOuCancelarReserva(int ReservaID, string justificacao, string tipoPedido, string email) {
            object[] results = this.Invoke("AlterarOuCancelarReserva", new object[] {
                        ReservaID,
                        justificacao,
                        tipoPedido,
                        email});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void AlterarOuCancelarReservaAsync(int ReservaID, string justificacao, string tipoPedido, string email) {
            this.AlterarOuCancelarReservaAsync(ReservaID, justificacao, tipoPedido, email, null);
        }
        
        /// <remarks/>
        public void AlterarOuCancelarReservaAsync(int ReservaID, string justificacao, string tipoPedido, string email, object userState) {
            if ((this.AlterarOuCancelarReservaOperationCompleted == null)) {
                this.AlterarOuCancelarReservaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAlterarOuCancelarReservaOperationCompleted);
            }
            this.InvokeAsync("AlterarOuCancelarReserva", new object[] {
                        ReservaID,
                        justificacao,
                        tipoPedido,
                        email}, this.AlterarOuCancelarReservaOperationCompleted, userState);
        }
        
        private void OnAlterarOuCancelarReservaOperationCompleted(object arg) {
            if ((this.AlterarOuCancelarReservaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AlterarOuCancelarReservaCompleted(this, new AlterarOuCancelarReservaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void CriarReservaCompletedEventHandler(object sender, CriarReservaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CriarReservaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CriarReservaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void AlterarOuCancelarReservaCompletedEventHandler(object sender, AlterarOuCancelarReservaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AlterarOuCancelarReservaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AlterarOuCancelarReservaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591