//------------------------------------------------------------------------------
// <auto-generated>
//     Este código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações a este ficheiro poderão provocar um comportamento incorrecto e perder-se-ão se
//     o código for regenerado.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Este código-fonte foi gerado automaticamente por Microsoft.VSDesigner, Versão 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace FormsGestaoHotelariaAPISoap.ServiceGestor {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="GestaoHotelariaGestorSoap", Namespace="http://www.ipca.pt/gestaohotelaria/gestor")]
    public partial class GestaoHotelariaGestor : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback AprovarReservaOperationCompleted;
        
        private System.Threading.SendOrPostCallback AprovarOuRejeitarPedidoOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConcluirReservaOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public GestaoHotelariaGestor() {
            this.Url = global::FormsGestaoHotelariaAPISoap.Properties.Settings.Default.FormsGestaoHotelariaAPISoap_ServiceGestor_GestaoHotelariaGestor;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event AprovarReservaCompletedEventHandler AprovarReservaCompleted;
        
        /// <remarks/>
        public event AprovarOuRejeitarPedidoCompletedEventHandler AprovarOuRejeitarPedidoCompleted;
        
        /// <remarks/>
        public event ConcluirReservaCompletedEventHandler ConcluirReservaCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.ipca.pt/gestaohotelaria/gestor/AprovarReserva", RequestNamespace="http://www.ipca.pt/gestaohotelaria/gestor", ResponseNamespace="http://www.ipca.pt/gestaohotelaria/gestor", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string AprovarReserva(int ReservaID) {
            object[] results = this.Invoke("AprovarReserva", new object[] {
                        ReservaID});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void AprovarReservaAsync(int ReservaID) {
            this.AprovarReservaAsync(ReservaID, null);
        }
        
        /// <remarks/>
        public void AprovarReservaAsync(int ReservaID, object userState) {
            if ((this.AprovarReservaOperationCompleted == null)) {
                this.AprovarReservaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAprovarReservaOperationCompleted);
            }
            this.InvokeAsync("AprovarReserva", new object[] {
                        ReservaID}, this.AprovarReservaOperationCompleted, userState);
        }
        
        private void OnAprovarReservaOperationCompleted(object arg) {
            if ((this.AprovarReservaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AprovarReservaCompleted(this, new AprovarReservaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.ipca.pt/gestaohotelaria/gestor/AprovarOuRejeitarPedido", RequestNamespace="http://www.ipca.pt/gestaohotelaria/gestor", ResponseNamespace="http://www.ipca.pt/gestaohotelaria/gestor", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string AprovarOuRejeitarPedido(int PedidoID, bool isApproved) {
            object[] results = this.Invoke("AprovarOuRejeitarPedido", new object[] {
                        PedidoID,
                        isApproved});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void AprovarOuRejeitarPedidoAsync(int PedidoID, bool isApproved) {
            this.AprovarOuRejeitarPedidoAsync(PedidoID, isApproved, null);
        }
        
        /// <remarks/>
        public void AprovarOuRejeitarPedidoAsync(int PedidoID, bool isApproved, object userState) {
            if ((this.AprovarOuRejeitarPedidoOperationCompleted == null)) {
                this.AprovarOuRejeitarPedidoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAprovarOuRejeitarPedidoOperationCompleted);
            }
            this.InvokeAsync("AprovarOuRejeitarPedido", new object[] {
                        PedidoID,
                        isApproved}, this.AprovarOuRejeitarPedidoOperationCompleted, userState);
        }
        
        private void OnAprovarOuRejeitarPedidoOperationCompleted(object arg) {
            if ((this.AprovarOuRejeitarPedidoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AprovarOuRejeitarPedidoCompleted(this, new AprovarOuRejeitarPedidoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.ipca.pt/gestaohotelaria/gestor/ConcluirReserva", RequestNamespace="http://www.ipca.pt/gestaohotelaria/gestor", ResponseNamespace="http://www.ipca.pt/gestaohotelaria/gestor", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ConcluirReserva(int ReservaID) {
            object[] results = this.Invoke("ConcluirReserva", new object[] {
                        ReservaID});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ConcluirReservaAsync(int ReservaID) {
            this.ConcluirReservaAsync(ReservaID, null);
        }
        
        /// <remarks/>
        public void ConcluirReservaAsync(int ReservaID, object userState) {
            if ((this.ConcluirReservaOperationCompleted == null)) {
                this.ConcluirReservaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConcluirReservaOperationCompleted);
            }
            this.InvokeAsync("ConcluirReserva", new object[] {
                        ReservaID}, this.ConcluirReservaOperationCompleted, userState);
        }
        
        private void OnConcluirReservaOperationCompleted(object arg) {
            if ((this.ConcluirReservaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConcluirReservaCompleted(this, new ConcluirReservaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void AprovarReservaCompletedEventHandler(object sender, AprovarReservaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AprovarReservaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AprovarReservaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void AprovarOuRejeitarPedidoCompletedEventHandler(object sender, AprovarOuRejeitarPedidoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AprovarOuRejeitarPedidoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AprovarOuRejeitarPedidoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void ConcluirReservaCompletedEventHandler(object sender, ConcluirReservaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConcluirReservaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConcluirReservaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591